kernel: fix crypto: talitos - rename first/last to first_desc/last_desc
backported upstream commit a1b80018b8cec27fc06a8b04a7f8b5f6cfe86eae
renames last to last_desc but misses this occurance which leads to compile errors on mpc85xx

drivers/crypto/talitos.c: In function 'ahash_digest':
drivers/crypto/talitos.c:2204:16: error: 'struct talitos_ahash_req_ctx' has no member named 'last'
 2204 |         req_ctx->last = 1;
      |                ^~

Fixes: 	a866e2b1c65e ("crypto: talitos - rename first/last to first_desc/last_desc")
Signed-off-by: Goetz Goerisch <ggoerisch@gmail.com>