ead: add libbsd as build dependency
The final binary is missing symbols without libbsd
due to libpcap using functions strlcat and strlcpy:

  pcap-rpcap.c:(.text+0x2c54): undefined reference to `strlcat'
  sockutils.c:(.text+0xb51): undefined reference to `strlcpy'
  gencode.c:(.text+0x73b): undefined reference to `strlcpy'
  nametoaddr.c:(.text+0x4e1): undefined reference to `strlcpy'

Add a dependency to build libbsd and link the shared libbsd library.

Signed-off-by: Michael Pratt <mcpratt@pm.me>