mediatek: add CMCC RAX3000Me support
This is a draft which I need community help with. Cherry-picked from https://github.com/immortalwrt/immortalwrt/commit/57f31cd5b11cb7e590c330845ec74ffa2d6eb13e

I own 2 CMCC RAX3000Me devices, I had to solder an UART pins for both of them. I can build and install ImmortalWrt without any issues but when I build this PR in OpenWrt it does not boot. Using ImmortalWrt BL2 and FIP there is something with fit image I guess because boot stops at
```
[    1.362592] Waiting for root device /dev/fit0...
[   12.128099] platform fitblk: deferred probe pending
[   12.132979] platform 15100000.ethernet: deferred probe pending
```

If I flash BL2 and FIP from my OpenWrt build it even stops at
```
NOTICE:  BL2: v2.10.0   (release):OpenWrt v2024.01.17~bacca82a-3 (mt7981-spim-nand-ddr3)
NOTICE:  BL2: Built : 20:40:36, Jun 23 2025
NOTICE:  WDT: [40000000] Software reset (reboot)
NOTICE:  EMI: Using DDR3 settings
NOTICE:  EMI: Detected DRAM size: 512MB
NOTICE:  EMI: complex R/W mem test passed
NOTICE:  CPU: MT7981 (1300MHz)
NOTICE:  Couldn't find a valid ONFI parameter page, try bitwise majority to recover it
ERROR:   Parameter page recovery failed, aborting
ERROR:   Parameter page check failed
NOTICE:  SPI_NAND parses attributes from parameter page.
NOTICE:  SPI_NAND Detected ID 0xff
NOTICE:  Page size -1, Block size 1, size 4294967041
ERROR:   nand_read(0) failed with -22. 0 bytes read
ERROR:   nand_read(0) failed with -22. 0 bytes read
ERROR:   BL2: Failed to load image id 3 (-5)
```

We have many many devices here which I want to work properly on vanilla official OpenWrt.