config: loongarch64,powerpc64,riscv64: fix missing seccomp support
Changes done in commit 4c65359af49b ("build: fix including busybox,
procd and apk/opkg in imagebuilder") exposed missing seccomp support
issue for loongarch64, d1, qoriq, sifiveu and starfive targets as builds
for targets using those architectures started to fail:

 ERROR: unable to select packages:
  procd-seccomp (no such package):
    required by: base-files-1637~efc0c4666b[procd-seccomp]

Its happening as procd-seccomp depends on @SECCOMP config symbol, which
is not set on those architectures. So lets fix it by enabling this

Fixes: 080a769b4da8 ("qoriq: new target")
Fixes: 99545b4bb1fa ("d1: add new target")
Fixes: 7fcb82665e96 ("loongarch64: new target")
Fixes: a3469a90c47e ("sifiveu: add new target for SiFive U-based boards")
Fixes: 4070e2a64c52 ("starfive: add new target for StarFive JH7100/7110 SoC")
Fixes: 4c65359af49b ("build: fix including busybox, procd and apk/opkg in imagebuilder")
Signed-off-by: Petr Štetiar <ynezz@true.cz>