brcm47xx: fix 831-old_gpio_wdt.patch for linux 4.19
Fix the following compilation error when using linux 4.19 on brcm47xx:
drivers/watchdog/old_gpio_wdt.c:236:2: error: implicit declaration of function 'setup_timer'

setup_timer was removed and replaced by timer_setup in linux >=4.15:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=513ae785

Update the patch to use the timer_setup interface

Signed-off-by: Zachary Cook <zachcook1991@gmail.com>