config: powerpc64: fix missing seccomp support on qoriq target
Changes done in commit 4c65359af49b ("build: fix including busybox,
procd and apk/opkg in imagebuilder") exposed missing seccomp support
issue:

 ERROR: unable to select packages:
  procd-seccomp (no such package):
    required by: base-files-1637~efc0c4666b[procd-seccomp]

Its happening as procd-seccomp depends on @SECCOMP config symbol, which
is not set. So lets fix it by enabling this feature.

Fixes: 080a769b4da8 ("qoriq: new target")
Fixes: 4c65359af49b ("build: fix including busybox, procd and apk/opkg in imagebuilder")
Signed-off-by: Petr Štetiar <ynezz@true.cz>