ramips: esw_rt3050: fix uninitialized variable build error
This patch fixes the following build error:

drivers/net/ethernet/ralink/esw_rt3050.c: In function 'rt3050_esw_init':
drivers/net/ethernet/ralink/esw_rt3050.c:1467:12: error: 'pdev' is used uninitialized [-Werror=uninitialized]
 1467 |         if (!pdev)
      |            ^
drivers/net/ethernet/ralink/esw_rt3050.c:1461:33: note: 'pdev' was declared here
 1461 |         struct platform_device *pdev;
      |                                 ^~~~

Fixes: 4ffd5aa239c1 ("treewide: fix coccinelle checks")
Signed-off-by: Shiji Yang <yangshiji66@outlook.com>