apk: drop patch causing mkndx failures
A bug in the recent alignment changes caused the package indexes to
intermittently fail to generate during builds with something like:

ERROR: python3-botocore-1.31.7-r1.apk: unexpected end of file
ERROR: 1 errors, not creating index

Packages having a header size greater than the read buffer size of 128KB
but less than 160KB (128KB + (128KB / 4)) were affected.

In practice, this appears to be python3-botocore and
golang-github-jedisct1-dnscrypt-proxy2-dev.

Fixes: 64ec08eee1 ("apk: backport upstream fixes for unaligned access")
Signed-off-by: Matt Merhar <mattmerhar@protonmail.com>