e2fsprogs: link with library libcom_err
When compiling a package that depends on libext2fs, a linker error is
thrown:

    libext2fs.so: undefined reference to_et_list'
    libext2fs.so: undefined reference to com_err'

The package makefile for e2fsprogs overwrites the additional
libraries that have to be linked in libext2fs by re-defining the
ELF_OTHER_LIBS variable. Libcom_err was missed here.

Signed-off-by: Matthias Franck <matthias.franck@softathome.com>