xdp-tools: mark as nonshared
The SDK does not have the LLVM toolchain yet?

Hopefully fixes errors in the form:
  xsk_def_xdp_prog.c:4:10: fatal error: 'bpf/bpf_helpers.h' file not found
  #include <bpf/bpf_helpers.h>

Fixes: 6ad1bea2a603 ("xdp-tools: add package")

Signed-off-by: Nick Hainke <vincent@systemli.org>