imagebuilder: add missing support to declare packages to skip
Support to declare packages that are meant to be skipped for installation
if they are marked with tilde (~) was added for regular building, but it
was not added in imagebuilder as well.

Layerscape target uses this feature to mark certain packages which are part
of the DEVICE_PACKAGES and thus imagebuilder also tries to install them
but it will fail with:
ERROR: '~trusted-firmware-a-ls1012a-frdm' is not a valid world dependency, format is name(@tag)([<>~=]version)

Since packages marked with tilde prefix are not stripped from the package
list in imagebuilder.

So, lets add the same feature to imagebuilder as well.

Fixes: #18412
Fixes: #18411
Fixes: 377b66990b97 ("build: introduce support to declare skip package")
Signed-off-by: Robert Marko <robimarko@gmail.com>