ead: add include path for libpcap dependency
On systems that do not also have a pcap.h
installed in their default header search paths,
compilation stops with missing header:

  ead.c:26:10: fatal error: pcap.h: No such file or directory

Add the explicit path to the header in the staging directory.

Signed-off-by: Michael Pratt <mcpratt@pm.me>