generic: mikrotik: avoid 64-bit module breakage
The use of a modulo operation on 64-bit integers broke the build on
32-bit targets which do not provide such operations.

Seen on the buildbots as:
mips-openwrt-linux-musl-ld: drivers/mtd/parsers/routerbootpart.o:
in function `routerboot_partitions_parse':
drivers/mtd/parsers/routerbootpart.c:
(.text.routerboot_partitions_parse+0x58c):
undefined reference to `__umoddi3'

Fix this by using mtd_mod_by_eb() instead of open-coding the alginment
check.

Fixes: ada1dcb2b4 ("generic: mikrotik: size RouterBoot partitions so they are usable")
Signed-off-by: Daniel Golle <daniel@makrotopia.org>