netfilter: add missing symbol to kmod-nf-ipt
When kmod-nf-ipt is enabled, but kmod-ipt-core and kmod-nf-nat are not,
build fails due to a missing kernel module:

ERROR: module '/home/stijn/Development/OpenWrt/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/linux-6.12.54/net/ipv4/netfilter/ip_tables.ko' is missing.

Fix this by adding the CONFIG_IP_NF_IPTABLES_LEGACY symbol that will be
made user selectable by backporting an upstream patch.

Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>