apk: hardcode uclient-fetch instead of wget
Both wget-ssl and wget-nossl provide @wget-any that apk depends on and
both are valid choices for users to install. However, wget-nossl lacks
TLS support which makes installing and updating packages impossible.
Making wget-nossl have lower alternative priority than uclient-fetch
defeats the purpose of installing it, since uclient-fetch will be the
default alternative for wget.

Instead, patch apk to hardcode uclient-fetch to be always used instead
of wget, so users can install whichever wget variant they prefer.

Before:

root@OpenWrt:~# apk add wget-nossl
(1/2) Installing libpcre2 (10.47-r1)
  Executing libpcre2-10.47-r1.post-install
(2/2) Installing wget-nossl (1.25.0-r4)
  Executing wget-nossl-1.25.0-r4.post-install
  * add alternative: /usr/bin/wget -> /usr/libexec/wget-nossl
OK: 18.7 MiB in 153 packages
root@OpenWrt:~# apk update
ERROR: wget: exited with error 1
WARNING: updating https://downloads.openwrt.org/snapshots/targets/x86/64/packages/packages.adb: unexpected end of file
ERROR: wget: exited with error 1
WARNING: updating https://downloads.openwrt.org/snapshots/packages/x86_64/base/packages.adb: unexpected end of file
ERROR: wget: exited with error 1
WARNING: updating https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/6.12.77-1-c9fff994e410f83a85b5db92074f9dca/packages.adb: unexpected end of file
ERROR: wget: exited with error 1
WARNING: updating https://downloads.openwrt.org/snapshots/packages/x86_64/luci/packages.adb: unexpected end of file
ERROR: wget: exited with error 1
WARNING: updating https://downloads.openwrt.org/snapshots/packages/x86_64/packages/packages.adb: unexpected end of file
ERROR: wget: exited with error 1
WARNING: updating https://downloads.openwrt.org/snapshots/packages/x86_64/routing/packages.adb: unexpected end of file
ERROR: wget: exited with error 1
WARNING: updating https://downloads.openwrt.org/snapshots/packages/x86_64/telephony/packages.adb: unexpected end of file
ERROR: wget: exited with error 1
WARNING: updating https://downloads.openwrt.org/snapshots/packages/x86_64/video/packages.adb: unexpected end of file
 [https://downloads.openwrt.org/snapshots/targets/x86/64/packages/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/base/packages.adb]
 [https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/6.12.77-1-c9fff994e410f83a85b5db92074f9dca/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/luci/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/packages/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/routing/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/telephony/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/video/packages.adb]
0 unavailable, 8 stale; 10970 distinct packages available

After:

root@OpenWrt:/tmp# apk add wget-nossl
(1/2) Installing libpcre2 (10.47-r1)
  Executing libpcre2-10.47-r1.post-install
(2/2) Installing wget-nossl (1.25.0-r4)
  Executing wget-nossl-1.25.0-r4.post-install
  * add alternative: /usr/bin/wget -> /usr/libexec/wget-nossl
OK: 18.7 MiB in 153 packages
root@OpenWrt:/tmp# apk update
 [https://downloads.openwrt.org/snapshots/targets/x86/64/packages/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/base/packages.adb]
 [https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/6.12.77-1-c9fff994e410f83a85b5db92074f9dca/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/luci/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/packages/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/routing/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/telephony/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/x86_64/video/packages.adb]
OK: 10970 distinct packages available

Fixes: https://github.com/openwrt/openwrt/issues/14894
Fixes: https://github.com/openwrt/packages/issues/28920
Signed-off-by: George Sapkin <george@sapk.in>