netfilter: add missing symbol to kmod-nf-ipt6
When kmod-nf-ipt6 is enabled, but kmod-ip6tables and kmod-ipt-nat are
not, build fails due to a missing kernel module:

ERROR: module '/home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/linux-qoriq_generic/linux-6.12.67/net/ipv6/netfilter/ip6_tables.ko' is missing.

Fix this by adding the CONFIG_IP6_NF_IPTABLES_LEGACY symbol that will be
made user selectable by backporting an upstream patch.

Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>