fortify-headers: suppress stdio.h format warnings
Prevent build failures when compiling packages with FORTIFY_SOURCE and
-Werror=format-nonliteral by suppressing this warning within the fortified
stdio.h. These are warnings (treated as errors) like

..._musl/include/fortify/stdio.h: In function 'snprintf':
..._musl/include/fortify/stdio.h:101:9: error: format not a string literal,
  argument types not checked [-Werror=format-nonliteral]

Some packages (e.g. glib2) currently work around this by disabling
fortify-source entirely, which is not ideal.

Signed-off-by: Karsten Sperling <ksperling@apple.com>