binutils: upgrade to version 2.25
Fixes build:
config/tc-i386.c: In function 'build_modrm_byte':
config/tc-i386.c:6143:31: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
         && !op.bitfield.reg64 != 1

Contains this fix:
   https://sourceware.org/ml/binutils/2014-09/msg00095.html

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

SVN-Revision: 48003