uboot-bcm4908: fix build error on GCC >= 10
GCC versions 10 and up default to `-fno-common`, causing the build to fail
with the following error:

```
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
```

This patch mirrors the one in uboot-zync (8b870418).

Signed-off-by: Joseph C. Lehner <joseph.c.lehner@gmail.com>